"""ReportGenerator — 确定性 Markdown/JSON 审查报告

M2 验收：同输入 → 同报告。不依赖 LLM，纯模板渲染。
"""

import json
from app.models.issue import Issue
from app.models.evidence import Evidence
from app.models.run import TraceEntry


class ReportGenerator:
    """生成固定格式的审查报告。"""

    def markdown(
        self,
        change_set: dict,
        plan: dict,
        trace: list[TraceEntry],
        issues: list[Issue],
        evidence: list[Evidence],
        duration_ms: float,
    ) -> str:
        """生成 Markdown 审查报告。"""
        files = change_set.get("files", [])
        lines = [
            "# Code Review Report",
            "",
            f"**Base:** `{change_set.get('base', 'N/A')}` → **Head:** `{change_set.get('head', 'N/A')}`",
            f"**Duration:** {duration_ms / 1000:.1f}s",
            f"**Risk Level:** {plan.get('risk_level', 'N/A')}",
            "",
            "---",
            "",
            "## 1. Change Summary",
            "",
            f"| # | Type | File | +Added | -Deleted |",
            f"|---|---|---|---|---|",
        ]
        for f in files:
            lines.append(f"| | {f['change_type']} | `{f['path']}` | {f.get('added_lines', 0)} | {f.get('deleted_lines', 0)} |")
        if not files:
            lines.append("| | | (no changes) | 0 | 0 |")
        lines.append(f"\n**Total:** {len(files)} files changed.\n")

        # 2. Execution Trace
        lines.append("## 2. Execution Trace\n")
        lines.append("| Step | Status | Duration |")
        lines.append("|---|---|---|")
        for t in trace:
            dur = f"{t.duration_ms / 1000:.1f}s" if t.duration_ms else "-"
            emoji = "OK" if t.status == "success" else ("SKIP" if "skipped" in t.status else "FAIL")
            lines.append(f"| {t.step} | {emoji} | {dur} |")
        for rc in plan.get("reason_codes", []):
            lines.append(f"| _{rc}_ | — | — |")
        lines.append("")

        # 3. Issues
        lines.append(f"## 3. Issues ({len(issues)})\n")
        if not issues:
            lines.append("No issues found.\n")
        else:
            ev_dict = {e.id: e for e in evidence}
            for i, iss in enumerate(issues, 1):
                lines.append(f"### {i}. [{iss.severity.upper()}] {iss.title}\n")
                lines.append(f"- **File:** `{iss.file}:{iss.line}`")
                lines.append(f"- **Source:** {iss.source}")
                lines.append(f"- **Reason:** {iss.reason}")
                if iss.fix:
                    lines.append(f"- **Suggestion:** {iss.fix}")
                lines.append("")
                # 证据引用
                if iss.evidence_ids:
                    lines.append("**Evidence:**\n")
                    for eid in iss.evidence_ids:
                        ev = ev_dict.get(eid)
                        if ev:
                            lines.append(f"- `{eid}`: {ev.snippet}")
                    lines.append("")

        # 4. Plan Details
        lines.append("## 4. Plan Details\n")
        lines.append(f"- **Analyzers:** {', '.join(plan.get('analyzers', []))}")
        lines.append(f"- **RAG:** {plan.get('enable_rag', False)}")
        lines.append(f"- **LLM Review:** {plan.get('enable_llm_semantic_review', False)}")
        lines.append(f"- **Reason Codes:** {', '.join(plan.get('reason_codes', [])) or 'none'}")
        lines.append(f"- **Risk Level:** {plan.get('risk_level', 'N/A')}")
        lines.append("")
        lines.append("---")
        lines.append("*Report generated by RuleBasedPlanBuilder (M2 deterministic pipeline)*")

        return "\n".join(lines)

    def json_report(
        self,
        change_set: dict,
        plan: dict,
        trace: list[TraceEntry],
        issues: list[Issue],
        evidence: list[Evidence],
        duration_ms: float,
    ) -> str:
        """生成 JSON 审查报告。"""
        return json.dumps({
            "change_set": change_set,
            "plan": plan,
            "trace": [{"step": t.step, "status": t.status, "duration_ms": t.duration_ms} for t in trace],
            "issues": [i.to_dict() for i in issues],
            "evidence": [e.to_dict() for e in evidence],
            "duration_ms": duration_ms,
        }, ensure_ascii=False, indent=2)
